# Generated by Django 5.2 on 2025-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateField()),
                ('cnpj', models.CharField(max_length=18)),
                ('fornecedor', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('mercadoria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
