# Generated by Django 5.2 on 2025-04-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_notafiscal_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nota_fiscal',
        ),
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
