# Generated by Django 5.2 on 2025-05-02 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_remove_produto_nota_fiscal_delete_notafiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('mercadoria', models.CharField(default=0, max_length=100)),
                ('cubagem', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='mercadoria',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nota_fiscal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pedido',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_carro',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='transportadora',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='fornecedor',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.produto'),
        ),
    ]
