# Generated by Django 5.2 on 2025-05-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_produto_remove_agendamento_mercadoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='produto',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='fornecedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nota_fiscal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pedido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_carro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='transportadora',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AgendamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadoria', models.CharField(max_length=100)),
                ('quantidade', models.FloatField()),
                ('cubagem', models.FloatField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agendamentos.agendamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
