# Generated by Django 5.2 on 2025-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_remove_agendamento_produto_alter_agendamento_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoproduto',
            name='cubagem',
            field=models.FloatField(verbose_name='Cubagem'),
        ),
        migrations.AlterField(
            model_name='agendamentoproduto',
            name='mercadoria',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='agendamentoproduto',
            name='quantidade',
            field=models.FloatField(verbose_name='Quantidade'),
        ),
    ]
