# Generated by Django 5.2 on 2025-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_alter_agendamentoproduto_cubagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoproduto',
            name='nota_fiscal',
            field=models.FloatField(default=1, verbose_name='Nota fiscal'),
        ),
    ]
