# Generated by Django 5.2 on 2025-05-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_agendamentoproduto_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='galpao',
            field=models.CharField(choices=[('galpao1', 'galpão1'), ('galpao2', 'galpão2'), ('galpao3', 'galpão3'), ('galpãa4', 'galpão4')], default='galpao1', max_length=20, verbose_name='Galpão'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_carro',
            field=models.CharField(choices=[('vuc', 'VUC'), ('toco', 'Toco'), ('truck', 'Truck'), ('carreta', 'Carreta')], default='Truc', max_length=20, verbose_name='Tipo'),
        ),
    ]
