# Generated by Django 5.2 on 2025-05-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_agendamento_galpao_alter_agendamento_tipo_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='galpao',
            field=models.CharField(choices=[('galpao1', 'galpão1'), ('galpao2', 'galpão2'), ('galpao3', 'galpão3'), ('galpãa4', 'galpão4')], max_length=20, verbose_name='Galpão'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_carro',
            field=models.CharField(choices=[('vuc', 'VUC'), ('toco', 'Toco'), ('truck', 'Truck'), ('carreta', 'Carreta')], max_length=20, verbose_name='Tipo'),
        ),
    ]
