# Generated by Django 5.2 on 2025-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_alter_agendamento_galpao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nota_fiscal',
            field=models.CharField(max_length=100),
        ),
    ]
