# Generated by Django 5.2 on 2025-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_alter_agendamento_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoproduto',
            name='nota_fiscal',
            field=models.CharField(default=1, max_length=100, verbose_name='Nota fiscal'),
        ),
    ]
