# Generated by Django 5.2 on 2025-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_alter_agendamentoproduto_nota_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentoproduto',
            name='nota_fiscal',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='galpao',
            field=models.CharField(choices=[('galpao1', 'galpão1'), ('galpao2', 'galpão2'), ('galpao3', 'galpão3'), ('galpao4', 'galpão4')], max_length=20, verbose_name='Galpão'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado'), ('atrasado', 'Atrasado')], default='pendente', max_length=20),
        ),
    ]
