# Generated by Django 5.2 on 2025-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_remove_agendamentoproduto_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='galpao',
            field=models.CharField(blank=True, choices=[('galpao1', 'galpão1'), ('galpao2', 'galpão2'), ('galpao3', 'galpão3'), ('galpao4', 'galpão4')], max_length=20, null=True, verbose_name='Galpão'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
