# Generated by Django 5.2 on 2025-06-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_alter_agendamento_galpao_alter_agendamento_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='sem_limite_doca',
            field=models.BooleanField(default=False, verbose_name='Exceção ao limite de doca'),
        ),
    ]
